openapi: 3.0.0
info:
  title: 'Gestor de Condomínios'
  version: '0.1'
paths:
  /api/cidade/select:
    get:
      tags:
        - Cidade
      summary: 'Select de cidades com base na UF'
      operationId: d5a877b9e86e976c5ff880db4c60ae7d
      parameters:
        -
          name: uf
          in: query
          description: UF
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'Requisição bem-sucedida'
        '400':
          description: 'Requisição inválida, dados incorretos ou faltando parâmetros'
        '500':
          description: 'Erro interno do servidor'
      security:
        -
          api_key: []
  /api/estado/select:
    get:
      tags:
        - Estado
      summary: 'Select de estados'
      operationId: 7f456136329025d0f73b4c48d5c5e162
      responses:
        '200':
          description: 'Requisição bem-sucedida'
        '400':
          description: 'Requisição inválida, dados incorretos ou faltando parâmetros'
        '500':
          description: 'Erro interno do servidor'
      security:
        -
          api_key: []
  /api/home:
    get:
      tags:
        - Dashboard
      summary: 'Obter informações da página inicial do Dashboard'
      operationId: da714e881fb56ec0e396aa045fccc9f3
      responses:
        '200':
          description: 'Requisição bem-sucedida'
        '400':
          description: 'Requisição inválida, dados incorretos ou faltando parâmetros'
        '500':
          description: 'Erro interno do servidor'
  /api/pessoa:
    post:
      tags:
        - Pessoa
      summary: 'Realiza o cadastro completo de pessoa'
      operationId: 9c40273048c10b45151ec9c5d5ae795b
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                nome:
                  description: 'Nome do usuário'
                  type: string
                sobrenome:
                  description: 'Sobrenome do usuário'
                  type: string
                dt_nascimento:
                  description: 'Data de nascimento do usuário (YYYY-MM-DD)'
                  type: string
                sexo:
                  description: 'Sexo do usuário (M/F)'
                  type: string
                cpf:
                  description: 'CPF do usuário'
                  type: string
                naturalidade:
                  description: 'Cidade natal do usuário'
                  type: string
                rg:
                  description: 'Registro Geral (RG) do usuário'
                  type: string
                orgao_emissao:
                  description: 'Órgão emissor do RG'
                  type: string
                dt_emissao:
                  description: 'Data de emissão do RG (YYYY-MM-DD)'
                  type: string
                telefone:
                  description: 'Número de telefone do usuário'
                  type: string
                celular:
                  description: 'Número de telefone celular do usuário'
                  type: string
                email:
                  description: 'Endereço de e-mail do usuário'
                  type: string
                cep:
                  description: 'CEP do endereço do usuário'
                  type: string
                cidade:
                  description: 'Cidade do endereço do usuário'
                  type: string
                logradouro:
                  description: 'Nome da rua do endereço do usuário'
                  type: string
                bairro:
                  description: 'Bairro do endereço do usuário'
                  type: string
                numero:
                  description: 'Número do endereço do usuário'
                  type: string
                complemento:
                  description: 'Complemento do endereço (opcional)'
                  type: string
              type: object
      responses:
        '200':
          description: 'Requisição bem-sucedida'
        '400':
          description: 'Requisição inválida, dados incorretos ou faltando parâmetros'
        '500':
          description: 'Erro interno do servidor'
      security:
        -
          api_key: []
  /api/pessoa/listagem:
    get:
      tags:
        - Pessoa
      summary: 'Listagem de Pessoas do Sistema'
      operationId: f1f08873a8ada24c03b7b622d3555787
      parameters:
        -
          name: nome
          in: query
          description: Nome
          required: false
          schema:
            type: string
        -
          name: cpf
          in: query
          description: CPF
          required: false
          schema:
            type: string
        -
          name: rg
          in: query
          description: RG
          required: false
          schema:
            type: string
        -
          name: pagina
          in: query
          description: Página
          required: false
          schema:
            type: string
      responses:
        '200':
          description: 'Requisição bem-sucedida'
        '400':
          description: 'Requisição inválida, dados incorretos ou faltando parâmetros'
        '500':
          description: 'Erro interno do servidor'
      security:
        -
          api_key: []
  '/api/pessoa/{id}':
    get:
      tags:
        - Pessoa
      summary: 'Consultar Pessoa'
      operationId: b5bfe495f75795f98fe807d8908e286f
      parameters:
        -
          name: id
          in: path
          description: id
          required: false
          schema:
            type: string
      responses:
        '200':
          description: 'Requisição bem-sucedida'
        '400':
          description: 'Requisição inválida, dados incorretos ou faltando parâmetros'
        '500':
          description: 'Erro interno do servidor'
      security:
        -
          api_key: []
    put:
      tags:
        - Pessoa
      summary: 'Atualiza o cadastro completo de pessoa'
      operationId: 0068def3a7a5feed870db2ebfaf241fc
      parameters:
        -
          name: id
          in: path
          description: Id
          required: false
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                nome:
                  description: 'Nome do usuário'
                  type: string
                sobrenome:
                  description: 'Sobrenome do usuário'
                  type: string
                dt_nascimento:
                  description: 'Data de nascimento do usuário (YYYY-MM-DD)'
                  type: string
                sexo:
                  description: 'Sexo do usuário (M/F)'
                  type: string
                cpf:
                  description: 'CPF do usuário'
                  type: string
                naturalidade:
                  description: 'Cidade natal do usuário'
                  type: string
                rg:
                  description: 'Registro Geral (RG) do usuário'
                  type: string
                orgao_emissao:
                  description: 'Órgão emissor do RG'
                  type: string
                dt_emissao:
                  description: 'Data de emissão do RG (YYYY-MM-DD)'
                  type: string
                telefone:
                  description: 'Número de telefone do usuário'
                  type: string
                celular:
                  description: 'Número de telefone celular do usuário'
                  type: string
                email:
                  description: 'Endereço de e-mail do usuário'
                  type: string
                cep:
                  description: 'CEP do endereço do usuário'
                  type: string
                cidade:
                  description: 'Cidade do endereço do usuário'
                  type: string
                logradouro:
                  description: 'Nome da rua do endereço do usuário'
                  type: string
                bairro:
                  description: 'Bairro do endereço do usuário'
                  type: string
                numero:
                  description: 'Número do endereço do usuário'
                  type: string
                complemento:
                  description: 'Complemento do endereço (opcional)'
                  type: string
              type: object
      responses:
        '200':
          description: 'Requisição bem-sucedida'
        '400':
          description: 'Requisição inválida, dados incorretos ou faltando parâmetros'
        '500':
          description: 'Erro interno do servidor'
      security:
        -
          api_key: []
    delete:
      tags:
        - Pessoa
      summary: 'Excluir Pessoa do Sistema'
      operationId: 388de936be463437649ca57462607954
      parameters:
        -
          name: id
          in: path
          description: Id
          required: false
          schema:
            type: string
      responses:
        '200':
          description: 'Requisição bem-sucedida'
        '400':
          description: 'Requisição inválida, dados incorretos ou faltando parâmetros'
        '500':
          description: 'Erro interno do servidor'
      security:
        -
          api_key: []
  /api/login:
    post:
      tags:
        - Usuário
      summary: 'Realiza login e obtem token de autenticação para app'
      operationId: d414502c107102295aa03d827add7ada
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                cpf:
                  description: 'CPF do usuário para autenticação'
                  type: string
                senha:
                  description: 'Senha do usuário para autenticação'
                  type: string
              type: object
      responses:
        '200':
          description: 'Requisição bem-sucedida'
        '400':
          description: 'Requisição inválida, dados incorretos ou faltando parâmetros'
        '500':
          description: 'Erro interno do servidor'
      security:
        -
          api_key: []
  /api/gerar/adm:
    get:
      tags:
        - Usuário
      summary: 'Realiza geração de usuário administrador'
      operationId: 928e143d9c24d3d3d932a2a98ae6f891
      responses:
        '200':
          description: 'Requisição bem-sucedida'
        '400':
          description: 'Requisição inválida, dados incorretos ou faltando parâmetros'
        '500':
          description: 'Erro interno do servidor'
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: Authorization
      in: header
tags:
  -
    name: Cidade
    description: Cidade
  -
    name: Estado
    description: Estado
  -
    name: Dashboard
    description: Dashboard
  -
    name: Pessoa
    description: Pessoa
  -
    name: Usuário
    description: Usuário
