openapi: 3.0.0
info:
  title: 'Gestor de Condomínios'
  version: '0.1'
paths:
  /api/home:
    get:
      tags:
        - Dashboard
      summary: 'Obter informações da página inicial do Dashboard'
      operationId: da714e881fb56ec0e396aa045fccc9f3
      responses:
        '200':
          description: 'Requisição bem-sucedida'
        '400':
          description: 'Requisição inválida, dados incorretos ou faltando parâmetros'
        '500':
          description: 'Erro interno do servidor'
  /api/login:
    post:
      tags:
        - Usuário
      summary: 'Realiza login e obtem token de autenticação para app'
      operationId: d414502c107102295aa03d827add7ada
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                cpf:
                  description: 'CPF do usuário para autenticação'
                  type: string
                senha:
                  description: 'Senha do usuário para autenticação'
                  type: string
              type: object
      responses:
        '200':
          description: 'Requisição bem-sucedida'
        '400':
          description: 'Requisição inválida, dados incorretos ou faltando parâmetros'
        '500':
          description: 'Erro interno do servidor'
  /api/gerar/adm:
    get:
      tags:
        - Usuário
      summary: 'Realiza geração de usuário administrador'
      operationId: 928e143d9c24d3d3d932a2a98ae6f891
      responses:
        '200':
          description: 'Requisição bem-sucedida'
        '400':
          description: 'Requisição inválida, dados incorretos ou faltando parâmetros'
        '500':
          description: 'Erro interno do servidor'
tags:
  -
    name: Dashboard
    description: Dashboard
  -
    name: Usuário
    description: Usuário
